<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Migrations\AdminIdentityDb\**" />
    <Compile Remove="Pages\Admin\**" />
    <Content Remove="Migrations\AdminIdentityDb\**" />
    <Content Remove="Pages\Admin\**" />
    <EmbeddedResource Remove="Migrations\AdminIdentityDb\**" />
    <EmbeddedResource Remove="Pages\Admin\**" />
    <None Remove="Migrations\AdminIdentityDb\**" />
    <None Remove="Pages\Admin\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Facebook" Version="7.0.6" />
    <PackageReference Include="Microsoft.AspNet.WebApi.Core" Version="5.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.Google" Version="6.0.36" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="6.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="6.0.36" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="6.0.36">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="6.0.35" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="6.0.35">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.SqlServer.Server" Version="1.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="6.0.18" />
    <PackageReference Include="OpenIddict.AspNetCore" Version="5.8.0" />
    <PackageReference Include="OpenIddict.EntityFrameworkCore" Version="5.8.0" />
    <PackageReference Include="System.Linq.Async" Version="6.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Migrations\OpenIddict\" />
  </ItemGroup>

</Project>
